### ISSUE TITLE
Can't install alongside `tap-salesforce`

### ISSUE THREAD

**Issue by micaelbergeron** [singer-io/target-csv#13]
This project depends on `singer-python==2.1.4` but it seems the latest version is `5.1.1`.

This cause a dependency conflict when installing alongside `tap-salesforce` which depends on `singer-python==5.0.5`

Are these projects complying to semver? Can we change the dependencies to be lenient of patch releases, using `singer-python>=5.0.0`?

**Comment by briansloane** [comment]
Hey @micaelbergeron. It sounds like you are having issues due to conflicts in your environment. We recommend that you install each tap and target in a separate python environment as outlined here:

https://github.com/singer-io/getting-started/blob/master/docs/RUNNING_AND_DEVELOPING.md#running-a-singer-tap-with-a-singer-target

That being said, we could probably update the CSV targets version of singer-python but running in different environments will help when they become out of sync.

**Comment by micaelbergeron** [comment]
Thanks @briansloane will look into that.

**Comment by timvisher** [comment]
The blessed way to run taps and targets is to run each from their own `virtualenv`. That helps avoid exactly this kind of conflict. Hopefully that resolved the immediate issue here.
