### ISSUE TITLE
Unknown message type ACTIVATE_VERSION

### ISSUE THREAD

**Issue by micaelbergeron** [singer-io/target-csv#14]
Piping `tap-salesforce` into this target causes and exception with the following message:

    Exception: Unknown message type ACTIVATE_VERSION in message {'type': 'ACTIVATE_VERSION', 'stream': 'Custom_Type__c', 'version': 1527701425182}

This error seems to be non-fatal.

**Comment by briansloane** [comment]
Can you try bumping the singer-python dependency on target-csv to see if that resolves this issue?

**Comment by thompdre84** [comment]
The error happens in persist_lines, which doesn't have handling for 'type': 'ACTIVATE_VERSION'. I manually added the following code and that seems to have solved the issue for me when using the latest version of singer.
`elif t == 'ACTIVATE_VERSION':
            print(None)`

**Comment by timvisher** [comment]
I would expect the fix for this to be to change this from a `raise` to a `logger.warning`. In order to allow the singer spec to evolve without constantly having to hand hold it from here we shouldn't care when new message types are introduced. `ACTIVATE_VERSION` is meaningless in this `target` and so we don't care about it. `logger.warning` should be sufficient to allow someone to notice that they need to augment `target-csv` if a new message type is introduced that it needs to handle.

**Comment by robmoore** [comment]
Any chance this might make it to a new release sometime soon?

**Comment by timvisher** [comment]
Fixed in #18

**Comment by timvisher** [comment]
@robmoore Cheers. :) https://pypi.org/manage/project/target-csv/release/0.3.0/
