### ISSUE TITLE
Store data in csv files for currency rates

### ISSUE THREAD

**Issue by avinashsamala** [singer-io/target-csv#9]
Hi Team,
              I am trying to store data in csv file for currency exchange rates in given example in singer.io.
I installed python 3 and after executing below commands
› pip install target-csv tap-fixerio
› tap-fixerio | target-csv
but i am getting issue like below screen shot.
screen shot link: http://prntscr.com/g6nn5z

**Comment by joaomarcosgris** [comment]
Hey, I'm aware of this and I fixed it on pull request #8. Just waiting for the acceptance.

**Comment by cmerrick** [comment]
Hi there - it looks like you're using python2.7 rather than python3.  Checkout DigitalOcean's instructions for installing python3 on [macOS](https://www.digitalocean.com/community/tutorials/how-to-install-python-3-and-set-up-a-local-programming-environment-on-macos) and [ubuntu](https://www.digitalocean.com/community/tutorials/how-to-install-python-3-and-set-up-a-local-programming-environment-on-ubuntu-16-04)
